@startuml DiagramaDeClases

abstract class Pelicula {
    nombre
    elenco
    --
    presupuesto()
    sueldoDelElenco()
    ganancias()
    recaudacion()
    recaudacionExtra()
    rodarPelicula()
    esEconomica()
}

class PeliculaDeDrama extends Pelicula{
    presupuesto()
    sueldoDelElenco()
    ganancias()
    recaudacion()
    recaudacionExtra()
    rodarPelicula()
    esEconomica()
}

class PeliculaDeAccion extends Pelicula{
    vidriosRotos
    --
    presupuesto()
    sueldoDelElenco()
    ganancias()
    recaudacion()
    recaudacionExtra()
    rodarPelicula()
    esEconomica()
}

class PeliculaDeTerror extends Pelicula{
    cuchos
    --
    presupuesto()
    sueldoDelElenco()
    ganancias()
    recaudacion()
    recaudacionExtra()
    rodarPelicula()
    esEconomica()
}

class PeliculaDeComedia extends Pelicula{
    presupuesto()
    sueldoDelElenco()
    ganancias()
    recaudacion()
    recaudacionExtra()
    rodarPelicula()
    esEconomica()
}

class Actor {
    experiencia
    peliculasEnLasQueActuo
    ahorros
    --
    sueldo ()
    peliculasEnLasQueActuo()
    recategorizarse()
    experiencia()
    actuar()
}

interface experiencia {
    cuantoCobra(unActor)
    subirDeCategoria(unActor)
}

object amateur {
    cuantoCobra(unActor)
    subirDeCategoria(unActor)
}

object establecido {
    cuantoCobra(unActor)
    subirDeCategoria(unActor)
    nivelDeFama(unActor)
    nivelDeFamaMayorA(unActor,unaCantidad)
}

object estrella {
    cuantoCobra(unActor)
    subirDeCategoria(unActor)
}

object IMPdeP {
    peliculas 
    actores
    --
    actorMejorPago()
    peliculasEconomicas()
    nombresDeLasPeliculasEconomicas()
    gananciaDeLasPeliculasEconomicas()
    recategorizarActores()
}

Pelicula -r->"*" Actor 

Actor -r-> experiencia
amateur .d.|> experiencia
establecido .d.|> experiencia
estrella .d.|> experiencia

experiencia ..> Actor

IMPdeP -->"*" Actor
IMPdeP -->"*" Pelicula 

@enduml 